baseURL : "https://codetechdev.com/"
languageCode : "en-us"
title : "CodeTechDev"
theme : "PaperMod"

params:
  defaultTheme: auto
  title: CodeTechDev
  description: "Welcome to CTD"
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to CTD
  
  label:
        text: "CodeTechDev"
        icon: /CTD_small.png
        iconHeight: 35
  
  assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: /CTD_small.png
        favicon16x16: /CTD_small.png
        favicon32x32: /CTD_small.png
        apple_touch_icon: /CTD_small.png
        safari_pinned_tab: /CTD_small.png
  
  socialIcons:
        - name: twitter
          url: "https://twitter.com/codetechdev"
        - name: youtube
          url: "https://youtube.com"
        - name: github
          url: "https://github.com/codetechdev"
  
  fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

staticDir:
  - static

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: example
          name: example.org
          url: https://example.org
          weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary