baseURL : "https://codetechdev.com/"
languageCode : "en-us"
title : "CodeTechDev"
theme : "PaperMod"

params:
  homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to CTD
  
  label:
        text: "CodeTechDev"
        icon: /CTD_small.png
        iconHeight: 35
  
  assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: /CTD_small.png
        favicon16x16: /CTD_small.png
        favicon32x32: /CTD_small.png
        apple_touch_icon: /CTD_small.png
        safari_pinned_tab: /CTD_small.png
  
  socialIcons:
        - name: twitter
          url: "https://twitter.com/codetechdev"
        - name: youtube
          url: "https://youtube.com"
        - name: github
          url: "https://github.com/codetechdev"

staticDir:
  - static